<template>
    <v-app>
        <v-main>
            <v-container>
                <v-row>
                    <v-col>
                        <v-text-field
                            label="Student Number"
                            variant="outlined"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col
                        ols="12"
                        md="4"
                    >
                        <v-text-field
                            label="Last Name"
                            variant="outlined"
                        ></v-text-field>                
                    </v-col>
                    <v-col
                        cols="12"
                        md="4"
                    >
                        <v-text-field
                            label="First Name"
                            variant="outlined"
                        ></v-text-field>
                    </v-col>
                                        <v-col
                        cols="12"
                        md="4"
                    >
                        <v-text-field
                            label="Middle Name"
                            variant="outlined"
                        ></v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col
                        cols="12"
                        md="4"
                    >
                        <v-combobox
                            label="Course"
                            :items="['BSCS', 'DCT']"
                            variant="outlined"
                        ></v-combobox>
                    </v-col>
                    <v-col
                        cols="12"
                        md="4"
                    >
                        <v-combobox
                            label="Year"
                            :items="['1st Year', '2nd Year', '3rd Year', '4th Year']"
                            variant="outlined"
                        ></v-combobox>
                    </v-col>
                    <v-col
                        cols="12"
                        md="4"
                    >
                        <v-combobox
                            label="Section"
                            :items="['A', 'B', 'C', 'D']"
                            variant="outlined"
                        ></v-combobox>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col
                        cols="12"
                        md="4"
                    >
                        <v-text-field
                            label="Address"
                            variant="outlined"
                        ></v-text-field>
                    </v-col>
                    <v-col
                        cols="12"
                        md="4"
                    >
                        <v-text-field
                            label="Contact No."
                            variant="outlined"
                        ></v-text-field>
                    </v-col>
                    <v-col
                        cols="12"
                        md="4"
                    >
                        <v-combobox
                            label="Gender"
                            :items="['Male', 'Female', 'LGBTQ']"
                            variant="outlined"
                        ></v-combobox>
                    </v-col>
                </v-row>
            </v-container>
        </v-main>
    </v-app>
</template>